datagrids:
    base-frontend-payment-profiles-grid:
        extended_entity_name: 'Oro\Bundle\AuthorizeNetBundle\Entity\CustomerPaymentProfile'
        options:
            frontend: true
            entityHint: oro.authorize_net.frontend.payment_profile.datagrid.base-frontend-payment-profiles-grid.entity_hint
            entity_pagination: true
        mass_actions:
            delete:
                disabled: true
        source:
            type: orm
            query:
                select:
                    - profile.id
                    - profile.name
                    - profile.lastDigits
                    - profile.default
                from:
                    - { table: 'Oro\Bundle\AuthorizeNetBundle\Entity\CustomerPaymentProfile', alias: profile }
                where:
                    and:
                        - 'profile.customerUser = @oro_security.token_accessor->getUserId()'
                        - 'profile.type = :profileType'
            bind_parameters:
                - profileType
        columns:
            name:
                label: oro.authorize_net.frontend.payment_profile.fields.name.label
                required: true
            lastDigits:
                label: oro.authorize_net.frontend.payment_profile.fields.last_card_digits.label
                shortenableLabel: false
            default:
                label: oro.authorize_net.frontend.payment_profile.fields.default.label
                frontend_type: boolean
        properties:
            id: ~
            update_link:
                type:  url
                route: oro_authorize_net_payment_profile_frontend_update
                params: [ id ]
            delete_link:
                type:  url
                route: oro_authorize_net_payment_profile_frontend_delete
                params: [ id ]
        sorters:
            columns:
                name:
                    data_name: profile.name
        filters:
            columns:
                name:
                    type:      string
                    data_name: profile.name
        actions:
            update:
                type: navigate
                label: oro.grid.action.update
                link: update_link
                icon: pencil
            delete:
                type: ajaxdelete
                label: oro.grid.action.delete
                link: delete_link
                icon: trash

    frontend-creditcard-payment-profiles-grid:
        extends: base-frontend-payment-profiles-grid
        options:
            entityHint: oro.authorize_net.frontend.payment_profile.datagrid.frontend-creditcard-payment-profiles-grid.entity_hint
            gridViews:
                allLabel: oro.authorize_net.frontend.payment_profile.datagrid.creditcard.entity_grid_all_view_label

    frontend-echeck-payment-profiles-grid:
        extends: base-frontend-payment-profiles-grid
        options:
            entityHint: oro.authorize_net.frontend.payment_profile.datagrid.frontend-echeck-payment-profiles-grid.entity_hint
            gridViews:
                allLabel: oro.authorize_net.frontend.payment_profile.datagrid.echeck.entity_grid_all_view_label
        columns:
            lastDigits:
                label: oro.authorize_net.frontend.payment_profile.datagrid.fields.last_account_digits.label
                shortenableLabel: false
